"""
Modified components.py with visualization integration
This shows exactly where and how to integrate Context2Visual module
into the existing HSE Bot application

CHANGES FROM ORIGINAL:
1. Added import: from context2visual import generate_visualization
2. Added visualization block in query_sequence() between data retrieval and text analysis
"""

import streamlit as st
from awsconnection import load_data
from interactions import get_generated_query, analyze_observations
from transformations import transform_observation
from filters import STATUS, DIVISION, OBSERVATIONCAUSE

# ============================================================================
# NEW: Import visualization module
# ============================================================================
from context2visual import generate_visualization


def query_sequence(user_input, session_state: dict) -> None:
    """
    Enhanced query sequence with visualization support
    """
    
    # ========================================================================
    # STEP 1: Generate SQL Query (EXISTING CODE)
    # ========================================================================
    with st.spinner('Generating SQL Query based on your request...'):
        generated_query, _ = get_generated_query(user_input, session_state)
    
    with st.expander("Generated SQL Query", expanded=False):
        st.write(f"Query: {generated_query}")

    if not generated_query:
        st.error("No SQL query generated by LLM Agent")
        return
    
    # ========================================================================
    # STEP 2: Execute Query and Get DataFrame (EXISTING CODE)
    # ========================================================================
    with st.spinner('Running the generated SQL query against HSE database...'):
        df = load_data(generated_query, {})
        
        if len(df) == session_state.hard_limit:
            st.warning(f"""Data limit of {session_state.hard_limit} observations reached. 
                       Try adjusting your query and/or filters to get more specific results!""")
    
    with st.expander("Query Result", expanded=False):
        st.write("Query Result:")
        st.dataframe(df)
    
    # ========================================================================
    # STEP 3: Generate Visualization (NEW CODE - THIS IS YOUR ADDITION!)
    # ========================================================================
    with st.spinner('Generating visualization...'):
        try:
            fig = generate_visualization(user_input, df)
            
            if fig:
                st.subheader("📊 Visualization")
                st.plotly_chart(fig, use_container_width=True)
            # If fig is None, silently skip (no visualization appropriate)
            
        except Exception as e:
            # Silent failure - don't break the app if visualization fails
            st.warning(f"Visualization could not be generated: {e}")
            # Alternatively, use pass for completely silent failure:
            # pass
    
    # ========================================================================
    # STEP 4: Generate Text Analysis (EXISTING CODE - UNCHANGED)
    # ========================================================================
    with st.spinner('Analyzing the retrieved data...'):
        observations_sorted, columns, rows = transform_observation(df)
        result = analyze_observations(observations_sorted, user_input, columns, rows)
    
    if result:
        st.subheader("📝 Analysis")
        st.write(result)
    else:
        st.error("AI analysis failed - try again with a smaller dataset")


def sidebar(session_state: dict) -> None:
    """
    Sidebar for filters (UNCHANGED FROM ORIGINAL)
    """
    with st.sidebar:
        st.header("Filters")
        session_state.filters = {
            "Created": st.date_input("Created", []),
            "Status": st.selectbox("Status", STATUS),
            "Division": st.selectbox("Division", DIVISION),
            "Observationcause": st.selectbox("Observationcause", OBSERVATIONCAUSE),
        }
        st.markdown(
            """
            <div class="tooltip">ℹ️
                <span class="tooltiptext">EXPERIMENTAL: Increasing the limit may retrieve more data, but in extreme cases can crash the AI.</span>
            </div>
            """,
            unsafe_allow_html=True
        )            
        session_state.hard_limit = st.number_input(
            "Hard Limit for Observations returned", 
            value=300, 
            min_value=1
        )